/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERCMKTPFactoryGetSet } from "./ERCMKTPFactoryGetSet";
export type { IEnftisNFT } from "./IEnftisNFT";
