/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IJWLX } from "./IJWLX";
export type { JWLMCFBase } from "./JWLMCFBase";
export type { JWLPayouts } from "./JWLPayouts";
export type { JWLRewards } from "./JWLRewards";
